---
driver:
  name: vagrant

provisioner:
  name: shell
  data_path: ./

platforms:
  - name: ubuntu-14.04
#   - name: centos-7.2

suites:
  - name: default
    provisioner:
      command_prefix: DROPBOX_ACCESS_TOKEN=<%= ENV['DROPBOX_ACCESS_TOKEN'] %>
      script: bootstrap.sh
