---
driver:
  name: vagrant

provisioner:
  name: shell
  data_path: ./
  sudo: false

verifier:
  sudo: false
  ruby_bindir: /usr/bin # http://qiita.com/sawanoboly/items/2874018f385dbe8562b1

platforms:
  - name: ubuntu-16.04
#   - name: centos-7.2

suites:
  - name: default
    provisioner:
      command_prefix: DROPBOX_ACCESS_TOKEN=<%= ENV['DROPBOX_ACCESS_TOKEN'] %>
      script: bootstrap.sh
