tet --universal --unpath --unexport _fish_abbr_ag 'ag --ignore-case'
set --universal --unpath --unexport _fish_abbr_agp 'ag --ignore-case --pager="less -iMR"'
set --universal --unpath --unexport _fish_abbr_cp 'cp -i'
set --universal --unpath --unexport _fish_abbr_d 'icdiff'
set --universal --unpath --unexport _fish_abbr_df 'df -h'
set --universal --unpath --unexport _fish_abbr_diff 'icdiff'
set --universal --unpath --unexport _fish_abbr_du 'du -h'
set --universal --unpath --unexport _fish_abbr_ga 'git add'
set --universal --unpath --unexport _fish_abbr_gb 'git branch'
set --universal --unpath --unexport _fish_abbr_gbal 'git branch -al'
set --universal --unpath --unexport _fish_abbr_gc 'git commit --verbose'
set --universal --unpath --unexport _fish_abbr_gca 'git commit --all --verbose'
set --universal --unpath --unexport _fish_abbr_gco 'git checkout'
set --universal --unpath --unexport _fish_abbr_gd 'git diff'
set --universal --unpath --unexport _fish_abbr_gdc 'git diff --cached'
set --universal --unpath --unexport _fish_abbr_glg 'git log --stat=300,300 --stat-graph-width=20'
set --universal --unpath --unexport _fish_abbr_glgp 'git log --stat=300,300 --stat-graph-width=20 --patch'
set --universal --unpath --unexport _fish_abbr_grep 'grep -i'
set --universal --unpath --unexport _fish_abbr_gst 'git status'
set --universal --unpath --unexport _fish_abbr_gsw 'git switch'
set --universal --unpath --unexport _fish_abbr_gswc 'git switch -c'
set --universal --unpath --unexport _fish_abbr_k 'kubectl'
set --universal --unpath --unexport _fish_abbr_less 'less -iMR'
set --universal --unpath --unexport _fish_abbr_lla 'ls -al'
set --universal --unpath --unexport _fish_abbr_mv 'mv -i'
set --universal --unpath --unexport _fish_abbr_mycli 'mycli --warn'
set --universal --unpath --unexport _fish_abbr_tree 'tree -CN'
